apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-2
spec:
  template:
    metadata:
      labels:
        app: deployment-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
